bridge:
  log_level: DEBUG #INFO

  default_seconds_until_timeout: <Timeout in seconds>

  cooldown_between_config_request_on_unknown_sensor: <Cooldown in seconds>

  serial:
    com_port: "<COM Port>"
    baudrate: 9600

  mqtt_client:
    username: "<mqtt username>"
    password: "<mqtt password>"
    address: "<mqtt address>"
    port: 1883

  influx:
    - <organisation 1>:
        url: "<influx url>"
        token: "<influx token>"
    - <organisation 2>:
        url: "<influx url>"
        token: "<influx token>"